language: python
sudo: false
python:
  - "2.7"
  
cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -q -r requirements.txt

script:
  - python --version
  - make test
