language: python
sudo: false
python:
  - "2.7"
  
cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -q -r requirements.txt

script:
  - python --version
  - pylint dashpi --rcfile=.pylintrc
#  - find ./dashpi/tests/ -name *.py | xargs pylint --rcfile=.pylintrc
